apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: cluster
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 3
    endpoint:
      host: 172.10.12.6
    machineGroupRef:
      kind: VSphereMachineConfig
      name: cluster-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: cluster
  gitOpsRef:
    kind: GitOpsConfig
    name: gitops-cluster
  kubernetesVersion: "1.22"
  managementCluster:
    name: cluster
  workerNodeGroupConfigurations:
  - count: 2
    machineGroupRef:
      kind: VSphereMachineConfig
      name: cluster
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: cluster
  namespace: default
spec:
  datacenter: CTEL-HNI
  insecure: true
  network: /CTEL-HNI/network/VM Network
  server: 172.10.12.10
  thumbprint: ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: cluster-cp
  namespace: default
spec:
  datastore: /CTEL-HNI/datastore/Database-02_ESXi-02
  diskGiB: 25
  folder: /CTEL-HNI/vm/eks-anywhere/k8s
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: /CTEL-HNI/host/Cluster-01/Resources
  template: /CTEL-HNI/vm/Templates/ubuntu-v1.22.6-kubernetes-1-22-eks-4-amd64-b7b3eb5
  users:
  - name: ubuntu
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCiWRWhKGExFEyGRa3ZwhnkcfL4dFjnnjlssFovZqc38D/1hxo9Q+VtTtPOA/5Iaxyg03O30Y+m/YN+gPIcciEK5kIOGTS+0ZX18OyJg3K9/ZBMLaTTSui0aQcQIqWxndnv/DIzmPEKt8vJxKgv+dSPs1R3V0vqtEclSCxbggdc0KJL5twojn/bsIEVSY5g4i4ej7Gsm8xN+rPK1GWxNg/zzD7nXvtuX56ESxYLsMdmgZbE3VoSMgVqb9LV8LCeBWl0nxpdCpqOEfUZ5G+Gjh6dW68gBqIKvaseZt59Pr4J1DeaBVTqVTlJ5pITDAHB0VFmfsbPqeyXiRcY8dgi9e+5

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: cluster
  namespace: default
spec:
  datastore: /CTEL-HNI/datastore/Database-02_ESXi-02
  diskGiB: 25
  folder: /CTEL-HNI/vm/eks-anywhere/k8s
  memoryMiB: 8192
  numCPUs: 4
  osFamily: ubuntu
  resourcePool: /CTEL-HNI/host/Cluster-01/Resources
  template: /CTEL-HNI/vm/Templates/ubuntu-v1.22.6-kubernetes-1-22-eks-4-amd64-b7b3eb5
  users:
  - name: ubuntu
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCiWRWhKGExFEyGRa3ZwhnkcfL4dFjnnjlssFovZqc38D/1hxo9Q+VtTtPOA/5Iaxyg03O30Y+m/YN+gPIcciEK5kIOGTS+0ZX18OyJg3K9/ZBMLaTTSui0aQcQIqWxndnv/DIzmPEKt8vJxKgv+dSPs1R3V0vqtEclSCxbggdc0KJL5twojn/bsIEVSY5g4i4ej7Gsm8xN+rPK1GWxNg/zzD7nXvtuX56ESxYLsMdmgZbE3VoSMgVqb9LV8LCeBWl0nxpdCpqOEfUZ5G+Gjh6dW68gBqIKvaseZt59Pr4J1DeaBVTqVTlJ5pITDAHB0VFmfsbPqeyXiRcY8dgi9e+5

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: GitOpsConfig
metadata:
  name: gitops-cluster
  namespace: default
spec:
  flux:
    github:
      branch: main
      clusterConfigPath: clusters/cluster
      fluxSystemNamespace: flux-system
      owner: duongbm
      personal: true
      repository: eks-anywhere-gitops

---
